=== theivanzheng/FundamentosProgramacionII/asignatura.xsd
<?xml version="1.0"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XmlSchema.xsd to edit this template
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="asignatura" type="tAsignaura"/>
    
    <xs:complexType name="tAsignaura">
        <xs:sequence>
            <xs:element name="nombreAsignatura" type="xs:string"/>
            <xs:element name="nCreditos"   type="xs:integer"/>  
            <xs:element name="curso"            type="tCurso"/> 
            <xs:element name="tipo"            type="tTipo"/>
            <xs:element name="alumnos"           type="tAlumno"      maxOccurs="unbounded"/>
            <xs:element name="profesor"         type="tProfesor"    maxOccurs="unbounded"/>
        </xs:sequence>
        
        <!-- Aquí van los atributos, pero como no hay no los pongo-->
    </xs:complexType>  
    
    <xs:complexType name="tAlumno">
        <xs:sequence>
            <xs:element name="nombre"       type="xs:string" />
            <xs:element name="apellidos"    type="xs:string" />
            <xs:element name="nota"         type="xs:decimal" minOccurs="0"/> <!-- POnemos que es 0 porque así puede estar o no estar-->
        </xs:sequence>
    </xs:complexType>  
    
    <xs:complexType name="tProfesor">
        <xs:sequence>
            <xs:element name="nombre"       type="xs:string" />
            <xs:element name="apellidos"    type="xs:string" />
            <xs:element name="nota"         type="xs:decimal" /> <!-- Consideramos que es un real-->
        </xs:sequence>
    </xs:complexType>  
    
    <xs:simpleType name="tCurso">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/> 
            <xs:maxINclusive value="4"/>
        </xs:restriction>
    </xs:simpleType>
           
    <xs:simpleType name="tTipo">
        <xs:restriction base="xs:string">
            <xs:enumeration value="optativa"/>
            <xs:enumeration value="obligatoria"/>
            <xs:enumeration value="instrumental"/>
        </xs:restriction>
    </xs:simpleType>       
    
     <xs:simpleType name="tNota">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0"/>
            <xs:maxinInclusive value="10"/>
        </xs:restriction>
    </xs:simpleType>  
       
</xs:schema>

=== theivanzheng/FundamentosProgramacionII/asignatura.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Almacenamos una asignatura
-->
<!--
<!DOCTYPE asignatura SYSTEM "asignaturaAlumnosDTD.dtd">
-->
<asignatura xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:noNamespaceSchemaLocation="asignatura.xsd">
    <nombreAsignatura>Fundamentos de programación II</nombreAsignatura>
    <nCreditos>6</nCreditos>
    <curso>1</curso>
    <tipo>obligatoria</tipo>
    <alumno>
        <nombre>Antonio</nombre>
        <apellidos>Martín Sánchez</apellidos>
        <nota>10</nota>
    </alumno>
    <alumno>
        <nombre>María</nombre>
        <apellidos>Martín Sánchez</apellidos>
        <nota>8</nota>
    </alumno>
    <alumno>
        <nombre>Lucas</nombre>
        <apellidos>Martín Sánchez</apellidos>
    </alumno>
    <profesor>
        <nombre>Encarna</nombre>
        <apellidos>Beato Gutiérrez</apellidos>
    </profesor>

</asignatura>
