=== theivanzheng/FundamentosProgramacionII/clinicaClaves.xsd
<?xml version="1.0"?>
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element  name="clinica" type="tClinica">
         <!-- keys globales --> 
        <xs:key name="medicoKey">
            <xs:selector xpath="medico"/>
            <xs:field xpath="@nColegiado"/>
        </xs:key>

        <xs:key name="pacienteKey">
            <xs:selector xpath="paciente"/>
            <xs:field xpath="nss"/>
        </xs:key>    

        <xs:keyref name="pacienteConsultaKeyRef" refer="pacienteKey">
            <xs:selector xpath="medico/turno/consulta"/>
            <xs:field xpath="paciente_consulta"/>
      
        </xs:keyref> 
    
    </xs:element>
       
    <xs:complexType name="tClinica">
        <xs:sequence>
        <xs:element name="medico" 
                    type="tmedico" 
                    maxOccurs="unbounded"/>
        <xs:element name="paciente"
                    type="tpaciente"
                    minOccurs="0" 
                    maxOccurs="unbounded"/>
        </xs:sequence>
        
    </xs:complexType>  
    
    <xs:complexType name="tmedico">
        <xs:sequence>
            <xs:element name="nombre" type="xs:string"/>
            <xs:element name="turno" type="tTurno" maxOccurs="unbounded"/>
        </xs:sequence>
          
        <xs:attribute name="nColegiado" type="tColegiado" use="required"/>    
        <xs:attribute name="especialidad" type="tEspecialidad" use="required"/>    
           
    </xs:complexType>
    
    <xs:simpleType name="tColegiado">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z][0-9]{4}"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="tEspecialidad">
        <xs:restriction base="xs:string">
                <xs:enumeration value="medicina interna"/>
                <xs:enumeration value="cardiologia"/>
                <xs:enumeration value="odontologia"/>
                <xs:enumeration value="traumatologia"/>
        </xs:restriction>
    </xs:simpleType>  
      
    <xs:complexType name="tTurno">
        <xs:sequence>
            <xs:element name="fecha" type="xs:date"/>
            <xs:element name="hora_ini" type="xs:time"/>
            <xs:element name="hora_fin" type="xs:time"/>
            <xs:element name="enfermero" type="xs:string"/>
            <xs:element name="consulta" type="tConsulta" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="tConsulta">
        <xs:sequence>
            <xs:element name="hora_cons" type="xs:string"/>
            <xs:element name="paciente_consulta" type="xs:string"/>
            <xs:element name="receta" type="treceta" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element name="importe" type="xs:decimal" minOccurs="0"/>       <!-- Por defecto maxOccurs=1-->
        </xs:sequence>
        
        <xs:attribute name="motivo" type="xs:string"/>    
    </xs:complexType>
    <xs:complexType name="treceta">
        <xs:sequence>
            <xs:element name="medicamento" type="xs:string"/>
            <xs:element name="posologia" type="xs:string"/>

        </xs:sequence>

    </xs:complexType>
        
         
    <xs:complexType name="tpaciente">
        <xs:sequence>
            <xs:element name="nss" type="xs:integer"/>
            <xs:element name="nombre" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    


</xs:schema>

=== theivanzheng/FundamentosProgramacionII/clinicaClaves.xml
<?xml version="1.0" encoding="UTF-8"?>
<clinica
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:noNamespaceSchemaLocation="clinicaClaves.xsd">
	<medico nColegiado="P2548" especialidad="odontologia">
		<nombre>Pepe</nombre>
		<turno>
			<fecha>2013-05-05</fecha>
			<hora_ini>08:00:00</hora_ini>
			<hora_fin>15:00:00</hora_fin>
			<enfermero>Juan</enfermero>
			<consulta motivo="revision">
				<hora_cons>09:15:00</hora_cons>
				<paciente_consulta>0088996987</paciente_consulta>
			</consulta>
			<consulta motivo="empaste pieza D2">
				<hora_cons>11:00:00</hora_cons>
				<paciente_consulta>0115660000</paciente_consulta>
                                <receta>
					<medicamento>penicilina</medicamento>
					<posologia>cada 8 horas</posologia>
				</receta>
				<importe>60</importe>
			</consulta>
		</turno>
		<turno>
			<fecha>2013-05-06</fecha>
			<hora_ini>16:00:00</hora_ini>
			<hora_fin>17:00:00</hora_fin>
			<enfermero>Maria</enfermero>
			<consulta motivo="desvitalizacion pieza M32">
				<hora_cons>16:20:00</hora_cons>
				<paciente_consulta>0088996987</paciente_consulta>
                                <receta>
					<medicamento>paracetamol</medicamento>
					<posologia>cada 8 horas</posologia>
				</receta>
				<receta>
					<medicamento>ibuprofeno</medicamento>
					<posologia>cada 8 horas</posologia>
				</receta>
				<importe>50</importe>
			</consulta>
		</turno>
	</medico>
	<medico nColegiado="N2548" especialidad="cardiologia">
		<nombre>Nuria</nombre>
		<turno>
			<fecha>2013-03-05</fecha>
			<hora_ini>08:00:00</hora_ini>
			<hora_fin>15:00:00</hora_fin>
			<enfermero>Esteban</enfermero>
			<consulta motivo="revision">
				<hora_cons>12:00:00</hora_cons>
				<paciente_consulta>0088996987</paciente_consulta>
                                <importe>100</importe>
			</consulta>
			<consulta motivo="bypass">
				<hora_cons>13:00:00</hora_cons>
				<paciente_consulta>9087654654</paciente_consulta>
                                <receta>
					<medicamento>adiro</medicamento>
					<posologia>uno al dia</posologia>
				</receta>
				<importe>1600.5</importe>
			</consulta>
		</turno>
		<turno>
			<fecha>2013-03-05</fecha>
			<hora_ini>16:00:00</hora_ini>
			<hora_fin>17:00:00</hora_fin>
			<enfermero>Maria</enfermero>
			<consulta motivo="electrocardiograma">
				<hora_cons>17:10:00</hora_cons>
				<paciente_consulta>0088996987</paciente_consulta>
                                <receta>
					<medicamento>heparina</medicamento>
					<posologia>uno al dia</posologia>
				</receta>
				<importe>50</importe>
			</consulta>
		</turno>
	</medico>
        <paciente>
		<nss>0088996987</nss>
		<nombre>Maria</nombre>
	</paciente>
        <paciente>
		<nss>0115660000</nss>
		<nombre>Rosa</nombre>
	</paciente>
        <paciente>
		<nss>9087654654</nss>
		<nombre>Jorge</nombre>
	</paciente>
</clinica>
