=== theivanzheng/FundamentosProgramacionII/mensajeriaApp.xsd
<?xml version="1.0"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XmlSchema.xsd to edit this template
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <xs:element name="mensajeria" type="tMensajeria">
        <xs:key name="usuarioKey">
            <xs:selector xpath="usuarios/usuario"/>
            <xs:field xpath="@login"/>
        </xs:key>
        <xs:key name="grupoLoginKey">
            <xs:selector xpath="grupos/grupo"/>
            <xs:field xpath="@login"/>
        </xs:key>   
     <xs:keyref name="bloqueadosKeyRef" refer="usuarioKey">
            <xs:selector xpath="./usuarios/usuario/bloqueados/bloqueado"/>
            <xs:field xpath="@user"/>
        </xs:keyref>
        

            
    </xs:element>
    
    <xs:complexType name="tMensajeria">
            <xs:sequence>
                <xs:element name="usuarios"     type="tUsuarios"/>
                <xs:element name="grupos"       type="tGrupos"      minOccurs="0"/>
                <xs:element name="mensajes"     type="tMensajes"/>
            </xs:sequence>
    </xs:complexType>
        
    
    <xs:complexType name="tUsuarios">
        <xs:sequence>
            <xs:element name="usuario" minOccurs="1" maxOccurs="unbounded" type="tUsuario">

            </xs:element>
        </xs:sequence>
        
    </xs:complexType>
    
    <xs:simpleType name="tLogin">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z][a-zA-Z0-9]*"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="tPassword">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z0-9]{8}[a-zA-Z0-9]*"/>
        </xs:restriction>
    </xs:simpleType>
    
    
    <xs:complexType name="tUsuario">
        <xs:sequence>
            <xs:element name="nombre" type="xs:string"/>
            <xs:element name="bloqueados" type="tBloqueados" minOccurs="0">
            
            </xs:element>
        </xs:sequence>
        <xs:attribute name="login" use="required" type="tLogin"/>
        <xs:attribute name="password" use="required" type="tPassword"/>
    </xs:complexType>
    
    <xs:complexType name="tBloqueados">
        <xs:sequence>
            <xs:element name="bloqueado"  type="tBloqueado" maxOccurs="unbounded">
                <xs:unique name="bloqueadoKey">
                    <xs:selector xpath="bloqueado"/>
                    <xs:field xpath="@user"/>
                </xs:unique>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="tBloqueado">
                <xs:attribute name="user" type="tLogin" use="required"/>

    </xs:complexType>
    
    <xs:complexType name="tGrupos">
        <xs:sequence>
            <xs:element name="grupo"    type="tGrupo" maxOccurs="unbounded" /> 
        </xs:sequence>   
    </xs:complexType>
    
    <xs:complexType name="tGrupo">
        <xs:sequence>
            <xs:element name="miembro" type="tMiembro" minOccurs="2" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="login" use="required" type="tLogin"/>
    </xs:complexType>
    
    <xs:complexType name="tMiembro">
        <xs:attribute name="usuario" type="xs:string" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="tMensajes">
        <xs:sequence>
            <xs:element name="mensaje" maxOccurs="unbounded" type="tMensaje"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="tMensaje">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
              <xs:element name="texto" type="tTexto"/>
               <xs:element name="video" type="xs:string"/>
               <xs:element name="imagen" type="xs:string"/>
        </xs:choice>           
                    <xs:attribute name="emisor"     type="xs:string"    use="required"/>
                    <xs:attribute name="receptor"   type="xs:string"    use="required"/>
                    <xs:attribute name="recibido"   type="xs:string"    use="optional" fixed="si"/>
                    <xs:attribute name="leido"      type="xs:string"    use="optional" fixed="si"/>
    </xs:complexType>
    
    <xs:complexType name="tTexto" mixed="true">
        <xs:sequence>
            <xs:element name="emoji" minOccurs="0" maxOccurs="unbounded" type="tEmoji"/>
        </xs:sequence>
    </xs:complexType>
  
    <xs:simpleType name="tEmoji">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9][0-9]?"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== theivanzheng/FundamentosProgramacionII/mesajeriaApp.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!-- DTD 
<!DOCTYPE mensajeria SYSTEM "mesajeriaApp.dtd">

-->


<mensajeria xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:noNamespaceSchemaLocation="mensajeriaApp.xsd"> 
<!-- SCHEMA
<mensajeria>-->
    <usuarios>
        <usuario login="ju123" password="123oo5678">
            <nombre>Julian</nombre>
            <bloqueados>
                <bloqueado user="mmm123"/>
                <bloqueado user="mmm123"/>

            </bloqueados>
        </usuario>
        <usuario login="mm123" password="1234avc78">
            <nombre>Maria</nombre>
            <bloqueados>
                <bloqueado user="lu123"/>
                <bloqueado user="lu123"/>
            </bloqueados>
        </usuario>
        <usuario login="lu123" password="aa345678">
            <nombre>Lucas</nombre>
            <bloqueados>
                <bloqueado user="mmm123"/>
            </bloqueados>
        </usuario>
        <usuario login="ant123" password="12345678">
            <nombre>Antonio</nombre>
            <bloqueados>
                <bloqueado user="mmm123"/>
            </bloqueados>
        </usuario>
        <usuario login="jul123" password="12345678">
            <nombre>Juli√°n</nombre>
            <bloqueados>
                <bloqueado user="mmm123"/>
            </bloqueados>
        </usuario>
        <usuario login="es123" password="12345678">
            <nombre>Esperanza</nombre>
            <bloqueados>
                <bloqueado user="mmm123"/>
            </bloqueados>
        </usuario>
        <usuario login="Man23" password="12345678">
            <nombre>Manuel</nombre>
        </usuario>
        <usuario login="rob123" password="12345678">
            <nombre>Roberto</nombre>
            <bloqueados>
                <bloqueado user="mmm123"/>
            </bloqueados>
        </usuario>
        <usuario login="fe123" password="12345678">
            <nombre>Fernando</nombre>
            <bloqueados>
                <bloqueado user="mmm123"/>
            </bloqueados>
        </usuario>
        <usuario login="lau123" password="12345678">
            <nombre>Laura</nombre>
            <bloqueados>
                <bloqueado user="mmm123"/>
            </bloqueados>
        </usuario>
        <usuario login="Pab123" password="12345678">
            <nombre>Pablo</nombre>
            <bloqueados>
                <bloqueado user="mmm123"/>
            </bloqueados>
        </usuario>
        <usuario login="ana123" password="12345678">
            <nombre>Ana</nombre>
            <bloqueados>
                <bloqueado user="mmm123"/>
            </bloqueados>
        </usuario>
        <usuario login="jm123" password="12345678">
            <nombre>Jose Manuel</nombre>
        </usuario>
        <usuario login="ru123" password="12345678">
            <nombre>Ruben</nombre>
            <bloqueados>
                <bloqueado user="mmm123"/>
                <bloqueado user="en123"/>
                <bloqueado user="jm123"/>
            </bloqueados>
        </usuario>
        <usuario login="en123" password="12345678">
            <nombre>Enrique</nombre>

        </usuario>

    </usuarios>
    <grupos>
        <grupo login="clase">
            <miembro usuario="ju123"/>
            <miembro usuario="ana123"/>
            <miembro usuario="jm123"/>
        </grupo>
        <grupo login="basket">
            <miembro usuario="ju123"/>
            <miembro usuario="lu123"/>
            <miembro usuario="jul123"/>
            <miembro usuario="en123"/>
        </grupo>
    </grupos>
    <mensajes>
        <mensaje emisor="ju123" receptor="ana123" recibido="si" leido="si">
            <texto>Donde estais? <emoji>22</emoji></texto>
            <imagen>cara.jpg</imagen>
        </mensaje>
        <mensaje emisor="ju123" receptor="jm123" recibido="si" leido="si">
            <texto>Donde estais? <emoji>22</emoji></texto>
            <imagen>cara.jpg</imagen>
            <video>cara.mov</video>
            <imagen>risa.jpg</imagen>
        </mensaje>
        <mensaje emisor="ju123" receptor="ana123" recibido="si">
            <texto>Donde estais?</texto>
            <video>champion.mov</video>
        </mensaje>
        <mensaje emisor="ant123" receptor="es123" recibido="si" leido="si">
            <texto>
                <emoji>99</emoji>
            </texto>
        </mensaje>
         <mensaje emisor="ant123" receptor="es123" recibido="si" leido="si">
           <texto>Os estamos esperando</texto>
        </mensaje>
         <mensaje emisor="ant123" receptor="es123" recibido="si" leido="si">
             <texto>
                 <emoji>21</emoji>
             </texto>
        </mensaje>
         <mensaje emisor="es123" receptor="ant123" recibido="si" leido="si">
           <texto>siiiii</texto>
        </mensaje>
        <mensaje emisor="es123" receptor="ant123" recibido="si">
            <texto>en 5 minutos <emoji>33</emoji><emoji>33</emoji></texto>
        </mensaje>
        <mensaje emisor="jm123" receptor="ant123" recibido="si">
           <texto>hola</texto>
        </mensaje>
    </mensajes>
    
</mensajeria>
