=== theivanzheng/FundamentosProgramacionII/notas.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT notas (nota*)>
<!ELEMENT nota (titulo,cuerpo)>
<!ELEMENT titulo (#PCDATA|n|c|s)*>
<!ELEMENT cuerpo (#PCDATA|n|c|s)*>
<!ELEMENT n (#PCDATA|c|s)*>
<!ELEMENT c (#PCDATA|n|s)*>
<!ELEMENT s (#PCDATA|n|c)*>

<!ATTLIST titulo tipoLetra (Times|Calibri|Courier) #REQUIRED
                 tamaño CDATA "11pt">
<!ATTLIST cuerpo tipoLetra (Times|Calibri|Courier) #REQUIRED
                 tamaño CDATA "11pt">

<!ELEMENT __ROOT__ ANY>
<!ATTLIST __ROOT__ version CDATA #REQUIRED>

=== theivanzheng/FundamentosProgramacionII/notas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE notas SYSTEM "notas.dtd">

<notas>
    <nota>
        <titulo tipoLetra="Times" tamaño="12pt">Lista de la <n>compra</n></titulo>
        <cuerpo tipoLetra ="Courier">
            Tomates.
            Patatas.
            Yogures.
        
            <n>Pañales.</n>
            Agua.
        </cuerpo>
    </nota>
    <nota>
        <titulo tipoLetra="Times" tamaño="14pt">Reyes Magos</titulo>
        <cuerpo tipoLetra ="Calibri" tamaño="11pt">
            Bolso (<n>Inés</n>).
            Zapatos (
                   <n>
                       <c>Laura</c> 
                   </n> )
            <n>FALTA Fernando.</n>
        </cuerpo>
    </nota>
        



</notas>
